# Generated by Django 6.0.2 on 2026-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
