# Generated by Django 6.0.2 on 2026-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_remove_category_id_category_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
